services:
  smurfbot:
    build:
      context: .
    image: smurfbot:latest
    container_name: smurfbot
    restart: unless-stopped
    init: true
    mem_limit: "200m"
    cpus: "0.5"
    volumes:
      - ./config.ini:/home/smurfbot/app/config.ini:ro
      - ./data:/home/smurfbot/data
